#!/usr/bin/env bash
# Install oarena v2 into its own venv and drop an `oarena` launcher on PATH.
#
# Why --system-site-packages:
#   oarena is a front-end for the fcode engine, which ships as a compiled
#   extension (fcode/fcode_engine.cpython-3XX-<arch>.so) inside whichever
#   interpreter you installed `fcode` into.  That .so is built for one exact
#   CPython version and there is no wheel we can pull it from ourselves, so
#   oarena must be able to see the ambient fcode installation.  The venv is
#   therefore created with --system-site-packages: oarena's own dependencies
#   (trueskill / click / rich) still get installed into ./.venv, but the
#   system + user site-packages of the base interpreter stay importable, which
#   is where `fcode` lives.  For the same reason we prefer the interpreter that
#   can already import fcode over merely the newest one on PATH.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="$HERE/.venv"
BIN="$HOME/.local/bin"

# --- pick an interpreter ----------------------------------------------------

usable() {  # >= 3.11, per pyproject's requires-python
    command -v "$1" >/dev/null 2>&1 &&
        "$1" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)' >/dev/null 2>&1
}
has_fcode() { "$1" -c 'import fcode' >/dev/null 2>&1; }

PY=""
FALLBACK=""
for c in python3 python3.13 python3.12 python3.11; do
    usable "$c" || continue
    [ -n "$FALLBACK" ] || FALLBACK="$c"
    if has_fcode "$c"; then PY="$c"; break; fi
done

if [ -z "$PY" ]; then
    PY="$FALLBACK"
    [ -n "$PY" ] || { echo "error: no python3 >= 3.11 found on PATH" >&2; exit 1; }
    echo "WARNING: no interpreter on PATH can import fcode; falling back to $PY" >&2
fi
echo "==> using $PY ($("$PY" --version 2>&1))"

# --- venv -------------------------------------------------------------------

if [ -x "$VENV/bin/python" ]; then
    have="$("$VENV/bin/python" -c 'import sys; print("%d.%d" % sys.version_info[:2])' 2>/dev/null || true)"
    want="$("$PY" -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
    if [ "$have" != "$want" ]; then
        echo "==> existing venv is python ${have:-unknown}, want $want -- recreating"
        rm -rf "$VENV"
    fi
fi

echo "==> creating venv at $VENV"
"$PY" -m venv --system-site-packages "$VENV"
"$VENV/bin/python" -m pip install --upgrade pip >/dev/null 2>&1 ||
    echo "note: could not upgrade pip (offline?) -- continuing"
"$VENV/bin/python" -m pip install -e "$HERE[dev]"

# --- fcode check (warn, never fail) -----------------------------------------

echo
if ! "$VENV/bin/python" - 2>/dev/null <<'PYEOF'
import pathlib

import fcode

root = pathlib.Path(fcode.__file__).parent
engine = sorted(root.glob("fcode_engine*.so")) + sorted(root.glob("fcode_engine*.pyd"))
print("==> fcode %s at %s" % (getattr(fcode, "__version__", "?"), root))
print("    engine: %s" % (engine[0].name if engine else "MISSING -- games will not run"))
PYEOF
then
    echo "WARNING: oarena's venv cannot import fcode." >&2
    echo "         oarena installs and runs, but every game will fail until you" >&2
    echo "         install the engine for this interpreter:" >&2
    echo >&2
    echo "             $PY -m pip install --user fcode" >&2
    echo >&2
    if command -v python3 >/dev/null 2>&1 && has_fcode python3; then
        echo "         (python3 CAN import fcode -- so this is a version mismatch:" >&2
        echo "          fcode's compiled engine is built for one exact CPython." >&2
        echo "          Re-run this script with that interpreter first on PATH.)" >&2
    fi
fi

# --- launcher ---------------------------------------------------------------

mkdir -p "$BIN"
cat > "$BIN/oarena" <<EOF
#!/usr/bin/env bash
# Generated by $HERE/install.sh
exec "$VENV/bin/oarena" "\$@"
EOF
chmod +x "$BIN/oarena"

cat > "$BIN/oarena-platform-sidecar" <<EOF
#!/usr/bin/env bash
# Generated by $HERE/install.sh
exec "$VENV/bin/python" -m oarena.platform_sidecar "\$@"
EOF
chmod +x "$BIN/oarena-platform-sidecar"

echo
echo "installed: $BIN/oarena  ->  $VENV/bin/oarena"
echo "installed: $BIN/oarena-platform-sidecar"
case ":$PATH:" in
    *":$BIN:"*) ;;
    *) echo "NOTE: add this to your shell rc:  export PATH=\"\$HOME/.local/bin:\$PATH\"";;
esac
echo
echo "next:  cd <your fcode project>   # the one with fcode.toml, bots/ and maps/"
echo "       oarena init"
echo "       oarena doctor"
echo "       oarena serve"
